server:
  port: 8081

spring:
  application:
    name: ai-agent
  profiles:
    active: @profiles.active@

agent:
  chat:
    timeout: 300_000

forest:
  variables:
    agent_base_url: http://localhost:8000

--- # nacos 配置
spring:
  cloud:
    nacos:
      server-addr: ${NACOS_ADDR:127.0.0.1:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      discovery:
        group: @nacos.discovery.group@
        namespace: ${spring.profiles.active}
      config:
        group: @nacos.config.group@
        namespace: ${spring.profiles.active}
  config:
    import:
      - optional:file:.env[.properties]
      - optional:nacos:application-common.yml
      - optional:nacos:${spring.application.name}.yml
